hl.on("hyprland.start", function()
	hl.dispatch(hl.dsp.focus({ workspace = 1 }))
	hl.exec_cmd("uwsm app -- hypridle")
	hl.exec_cmd("uwsm app -- mako")
	hl.exec_cmd("uwsm app -- waybar")
	hl.exec_cmd("uwsm app -- swaybg -i /home/simonm/myNixos/defaults/background.png -m fill")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
end)

hl.on("config.reloaded", function()
	hl.exec_cmd("pypr reload")
end)
